### ISSUE TITLE
Why a new messenger?

### ISSUE THREAD

**Issue by H5117** [ProfessorNavigator/communist#8]
Hi,

> Communist is a simple GTK 4 based p2p messenger. It uses torrent DHT combined with UDP hole punch technique to establish direct connection between users. Program can work in two modes: local network and internet, both IPv4 and IPv6 protocols are supported.

We already have [Tox](https://tox.chat/) and [Jami](https://jami.net/) with p2p archtecture and DHT. Why to create a new messenger instead of improving existing ones?

Also there is a library for p2p applications called [libp2p](https://libp2p.io/), which already solves most infrastructure tasks. It would be reasonable to use it instead of libcommunist.

**Comment by ProfessorNavigator** [comment]
> Why to create a new messenger instead of improving existing ones?

Why not? Everything is simple: if you do not like Communist - do not use it. If you don't like libcommunist - don't use it.
